### ISSUE TITLE
Your recent app submission was rejected for violating the permissions policy.

### ISSUE THREAD

**Issue by devfadl** [cakmakfatih/pin_view#10]
Hello guys , 
Trying to build my app with your package an error occurred when  upload APK on android play store 
"Your recent app submission was rejected for violating the permissions policy".

is there away to avoid using of these permissions when o don't need sms listener ?

**Comment by ganeshchenniah** [comment]
you have not used sms listeners and not mentioned any Permission for READ_SMS in manifest file right ?

**Comment by devfadl** [comment]
> you have not used sms listeners and not mentioned any Permission for READ_SMS in manifest file right ?

yes cause i don't need sms lisntner and need only the pin view

**Comment by AndrewPiterov** [comment]
Hi! Same problem when publish to Play Store - Requested permissions do not match core functionality of the app
I added these tree lines into manifest, and in "SMS and Call log permissions" page checked Core functionalities as Default Sms handler. 

    <uses-permission android:name="android.permission.SEND_SMS"/>    
    <uses-permission android:name="android.permission.READ_SMS"/>
    <uses-permission android:name="android.permission.RECEIVE_SMS"/>

I don't understand how to resolve this issue.

**Comment by ericel** [comment]
If I remember correctly, removing the above from your manifest may not be the only place you need to get rid of it.
Check also the sms package manifest when building for production to remove the below.
```
<uses-permission android:name="android.permission.SEND_SMS"/>    
<uses-permission android:name="android.permission.READ_SMS"/>
<uses-permission android:name="android.permission.RECEIVE_SMS"/>
```

**Comment by devfadl** [comment]
> <uses-permission android:name="android.permission.READ_SMS"/>
> <uses-permission android:name="android.permission.RECEIVE_SMS"/>

yes this is the solution Thanks
